// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Page() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>Encorians</title><script src=\"https://unpkg.com/htmx.org@1.9.10\"></script><script src=\"https://cdn.tailwindcss.com\"></script></head><body class=\"h-full w-full\"><form class=\"mx-auto w-1/2 mt-10 flex flex-col gap-2 justify-between\" hx-post=\"/encorian\" hx-target=\"#encorianslist\" hx-swap=\"innerHTML\"><section class=\"flex gap-2\"><input class=\"grow px-2 py-1 rounded-md border border-gray-200 outline-none focus:border-blue-200\" placeholder=\"Name\" type=\"text\" name=\"name\"> <input class=\"grow px-2 py-1 rounded-md border border-gray-200 outline-none focus:border-blue-200\" placeholder=\"Amount\" type=\"number\" name=\"pizzaAmount\"></section><button class=\"bg-blue-400 p-2 rounded-md w-full\">Add Pizza</button></form><div class=\"mt-5 mx-auto w-1/2\" hx-get=\"/encorian\" hx-target=\"#encoriansList\" hx-swap=\"innerHTML\" hx-trigger=\"load\"><h2 class=\"font-bold leading-normal text-[8rem] text-center bg-gradient-to-r from-purple-400 via-pink-500 to-red-500 text-transparent bg-clip-text font-bold text-3xl\">Encorians</h2><table class=\"w-full\"><thead><tr class=\"bg-gray-200\"><th class=\"border-r border-gray-300 \">Name</th><th class=\"border-r border-gray-300 \">Pizzas</th><th>Actions</th></tr></thead> <tbody id=\"encoriansList\"></tbody></table></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
